# Generated by Django 6.0.3 on 2026-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcessoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("pagina_acessada", models.CharField(max_length=500)),
                ("metodo_http", models.CharField(max_length=10)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Logs de Acesso",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Analise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_solicitante", models.CharField(max_length=200)),
                ("p1", models.BooleanField(default=False)),
                ("p2", models.BooleanField(default=False)),
                ("p3", models.BooleanField(default=False)),
                ("p4", models.BooleanField(default=False)),
                ("p5", models.BooleanField(default=False)),
                ("p6", models.BooleanField(default=False)),
                ("p7", models.BooleanField(default=False)),
                ("p8", models.BooleanField(default=False)),
                ("p9", models.BooleanField(default=False)),
                ("p10", models.BooleanField(default=False)),
                ("p11", models.BooleanField(default=False)),
                ("p12", models.BooleanField(default=False)),
                ("total_verdadeiras", models.IntegerField(default=0)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("APROVADO", "Aprovado"), ("REPROVADO", "Reprovado")],
                        max_length=10,
                    ),
                ),
                ("expressao_logica", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Análises",
                "ordering": ["-criado_em"],
            },
        ),
    ]
